title: "Piyush Bhardwaj"
email: "bhardwaaj.piyush@gmail.com"
description: >-
  ML Engineer | Applied Researcher
baseurl: "" 
url: "https://piyushbhardwaj.github.io"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-include-cache
katex: true	
author:
  name   : "Piyush Bhardwaj"
  avatar : "/assets/images/profile_pic.jpg"
  bio    : "ML Engineer | Interested in Quant Finance and Kernel Methods"
  location: "India"
  email: "bhardwaaj.piyush@gmail.com"
minimal_mistakes_skin: "dark"
include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      math: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      math: true
  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
